package com.company.rotations.models;

public enum AuditEventType {
    ALERT_INGESTED,
    ALERT_DEDUPLICATED,
    CREDENTIAL_VERIFIED,
    CREDENTIAL_EXPIRED,
    ROTATION_STARTED,
    ROTATION_COMPLETED,
    ROTATION_FAILED,
    ESCALATION_TRIGGERED,
    CREDENTIAL_ACCESSED
}
